version: "3.8"

services:
  backend:
    build: .
    container_name: oceanx_backend
    restart: always
    depends_on:
      - db
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - DB_HOST=db

  db:
    image: postgres:15-alpine
    container_name: oceanx_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"

volumes:
  postgres_data: